//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELL_TEST
    {
        public string CGI { get; set; }
        public string TYPE { get; set; }
        public string CELL_NAME { get; set; }
        public Nullable<int> BAND_ID { get; set; }
    }
}
