//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_BOARD_TYPE
    {
        public DATACOM_BOARD_TYPE()
        {
            this.DATACOM_BOARD = new HashSet<DATACOM_BOARD>();
        }
    
        public int ID { get; set; }
        public string ALIAS_NAME { get; set; }
        public string TYPE { get; set; }
        public Nullable<short> TOTAL_CHILD_NUMBER { get; set; }
    
        public virtual ICollection<DATACOM_BOARD> DATACOM_BOARD { get; set; }
    }
}
