//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_NE_SFP
    {
        public Nullable<int> ID { get; set; }
        public string TYPE { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public int NE_ID { get; set; }
    }
}
