//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_NE_AREA
    {
        public int ID { get; set; }
        public int NE_ID { get; set; }
        public int AREA_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RETIRE_DATE { get; set; }
    
        public virtual OPTICAL_AREA_ID_MAPPING OPTICAL_AREA_ID_MAPPING { get; set; }
        public virtual OPTICAL_NE OPTICAL_NE { get; set; }
    }
}
