//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_NE
    {
        public DATACOM_NE()
        {
            this.DATACOM_FINANCE_NE = new HashSet<DATACOM_FINANCE_NE>();
            this.DATACOM_WO_NE = new HashSet<DATACOM_WO_NE>();
            this.DATACOM_NE_BOARD = new HashSet<DATACOM_NE_BOARD>();
            this.DATACOM_NE_SITE = new HashSet<DATACOM_NE_SITE>();
        }
    
        public int ID { get; set; }
        public int TYPE_ID { get; set; }
        public decimal U2000_REF_ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS_NAME { get; set; }
        public string SUBRACK_TYPE { get; set; }
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string PATCH_VERSION { get; set; }
        public string LSR_ID { get; set; }
        public string REMARKS { get; set; }
        public Nullable<decimal> DEPLOYMENT_STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> FREE_BOARD { get; set; }
        public Nullable<int> SUB_CATEGORY_ID { get; set; }
    
        public virtual ICollection<DATACOM_FINANCE_NE> DATACOM_FINANCE_NE { get; set; }
        public virtual ICollection<DATACOM_WO_NE> DATACOM_WO_NE { get; set; }
        public virtual ICollection<DATACOM_NE_BOARD> DATACOM_NE_BOARD { get; set; }
        public virtual RIM_SUBCATEGORY RIM_SUBCATEGORY { get; set; }
        public virtual ICollection<DATACOM_NE_SITE> DATACOM_NE_SITE { get; set; }
    }
}
