//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIREWALL_BOARD
    {
        public int ID { get; set; }
        public int TYPE_ID { get; set; }
        public decimal SUBRACK_ID { get; set; }
        public Nullable<decimal> SLOT_ID { get; set; }
        public string HARDWARE_VERSION { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string REMARKS { get; set; }
        public string BARCODE { get; set; }
        public string BIOS_VERSION { get; set; }
        public string FPGA_VERSION { get; set; }
        public string STATUS { get; set; }
        public string BOM_ITEM { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> MANUFACTURE_DATE { get; set; }
        public Nullable<decimal> DEPLOYMENT_STATUS { get; set; }
    
        public virtual FIREWALL_BOARD_TYPE FIREWALL_BOARD_TYPE { get; set; }
    }
}
