//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_BOARD
    {
        public RADIO_BOARD()
        {
            this.RADIO_PORT = new HashSet<RADIO_PORT>();
            this.RADIO_SLOT_BOARD = new HashSet<RADIO_SLOT_BOARD>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BIOS_VEREX { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public string BIOSVER { get; set; }
        public string BOM_CODE { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public Nullable<int> SERIAL_NUMBER { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string HARDWARE_VERSION { get; set; }
        public string VENDOR_NAME { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public int RADIO_BOARD_TYPE_ID { get; set; }
    
        public virtual RADIO_BOARD_TYPE RADIO_BOARD_TYPE { get; set; }
        public virtual ICollection<RADIO_PORT> RADIO_PORT { get; set; }
        public virtual ICollection<RADIO_SLOT_BOARD> RADIO_SLOT_BOARD { get; set; }
    }
}
