//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_RACK
    {
        public RADIO_RACK()
        {
            this.RADIO_RACK_SUBRACK = new HashSet<RADIO_RACK_SUBRACK>();
            this.SITE_CANDIDATE_RACK = new HashSet<SITE_CANDIDATE_RACK>();
        }
    
        public int ID { get; set; }
        public int CABINET_NUMBER { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public string BOM_RACK_TYPE { get; set; }
        public string BOM_CODE { get; set; }
        public string VENDOR_NAME { get; set; }
        public string HARDWARE_VERSION { get; set; }
        public Nullable<int> INVENTORY_UNIT_ID { get; set; }
        public string INVENTORY_UNIT_TYPE { get; set; }
        public Nullable<System.DateTime> DATE_OF_LAST_SERVICE { get; set; }
        public string UNIT_POSITION { get; set; }
        public Nullable<int> ISSUE_NUMBER { get; set; }
        public string UNIT_POSITION_FULL { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public int RADIO_RACK_TYPE_ID { get; set; }
    
        public virtual RADIO_RACK_TYPE RADIO_RACK_TYPE { get; set; }
        public virtual ICollection<RADIO_RACK_SUBRACK> RADIO_RACK_SUBRACK { get; set; }
        public virtual ICollection<SITE_CANDIDATE_RACK> SITE_CANDIDATE_RACK { get; set; }
    }
}
