//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_RACK_SUBRACK
    {
        public int ID { get; set; }
        public int RADIO_SUBRACK_ID { get; set; }
        public int RADIO_RACK_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RETIRE_DATE { get; set; }
    
        public virtual RADIO_RACK RADIO_RACK { get; set; }
        public virtual RADIO_SUBRACK RADIO_SUBRACK { get; set; }
    }
}
