//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAN_CONTROLLER
    {
        public RAN_CONTROLLER()
        {
            this.RAN_CONTROLLER_RAN_HOSTVER = new HashSet<RAN_CONTROLLER_RAN_HOSTVER>();
            this.RAN_CONTROLLER_SITE_IDENTITY = new HashSet<RAN_CONTROLLER_SITE_IDENTITY>();
            this.RANCONTROLLER_RACK = new HashSet<RANCONTROLLER_RACK>();
        }
    
        public int ID { get; set; }
        public string NE_NAME { get; set; }
        public int RAN_NETYPE_ID { get; set; }
        public string IP { get; set; }
        public string INTERNAL_ID { get; set; }
        public Nullable<System.DateTime> CREATION_TIME { get; set; }
        public string NE_DN { get; set; }
        public string TIME_ZONE { get; set; }
        public Nullable<System.DateTime> FIRST_CONNECTION_TIME { get; set; }
        public string PHISICAL_LOCATION { get; set; }
        public string NE_DESCRIPTION { get; set; }
        public string VENDOR_NAME { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public string SOFTWARE_VERSION { get; set; }
    
        public virtual ICollection<RAN_CONTROLLER_RAN_HOSTVER> RAN_CONTROLLER_RAN_HOSTVER { get; set; }
        public virtual RAN_NETYPE RAN_NETYPE { get; set; }
        public virtual ICollection<RAN_CONTROLLER_SITE_IDENTITY> RAN_CONTROLLER_SITE_IDENTITY { get; set; }
        public virtual ICollection<RANCONTROLLER_RACK> RANCONTROLLER_RACK { get; set; }
    }
}
