//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAN_BOARD
    {
        public RAN_BOARD()
        {
            this.RAN_PORT = new HashSet<RAN_PORT>();
            this.RAN_SLOT_BOARD = new HashSet<RAN_SLOT_BOARD>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SLOT_NUMBER { get; set; }
        public string BOARD_TYPE { get; set; }
        public string BIOS_VER { get; set; }
        public string BIOS_VEREX { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_OF_LAST_SERVICE { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public Nullable<int> INVENTORY_UNIT_ID { get; set; }
        public string INVENTORY_UNIT_TYPE { get; set; }
        public string ISSUE_NUMBER { get; set; }
        public string BOM_CODE { get; set; }
        public string LAN_VER { get; set; }
        public string LOGIC_VER { get; set; }
        public string MBUS_VER { get; set; }
        public string SUBSLOT_NO { get; set; }
        public string MODULE_NO { get; set; }
        public string UNIT_POSITION { get; set; }
        public string VENDOR_UNIT_FAMILY_TYPE { get; set; }
        public Nullable<int> VENDOR_UNIT_TYPE_NUMBER { get; set; }
        public string VERSION_NUMBER { get; set; }
        public string VENDOR_NAME { get; set; }
        public string UNIT_POSITION_DETAIL { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public Nullable<int> SLOT_POSITION { get; set; }
        public int RAN_BOARD_TYPE_ID { get; set; }
        public int RAN_LOGICAL_FUNCT_TYPE_ID { get; set; }
        public int RAN_BOARD_CLASS_ID { get; set; }
        public int RAN_TYPE_POUC_TDM_ID { get; set; }
        public int RAN_PORT_WORK_MODE_ID { get; set; }
    
        public virtual RAN_BOARD_CLASS RAN_BOARD_CLASS { get; set; }
        public virtual RAN_BOARD_TYPE RAN_BOARD_TYPE { get; set; }
        public virtual RAN_LOGICAL_FUNCT_TYPE RAN_LOGICAL_FUNCT_TYPE { get; set; }
        public virtual RAN_PORT_WORK_MODE RAN_PORT_WORK_MODE { get; set; }
        public virtual RAN_TYPE_POUC_TDM RAN_TYPE_POUC_TDM { get; set; }
        public virtual ICollection<RAN_PORT> RAN_PORT { get; set; }
        public virtual ICollection<RAN_SLOT_BOARD> RAN_SLOT_BOARD { get; set; }
    }
}
