//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_CATEGORY
    {
        public RIM_CATEGORY()
        {
            this.RIM_CATEGORY_LEVEL = new HashSet<RIM_CATEGORY_LEVEL>();
            this.RIM_LEVELS = new HashSet<RIM_LEVELS>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CAT_ORDER { get; set; }
        public Nullable<int> MODULE_ID { get; set; }
    
        public virtual RIM_MODULES RIM_MODULES { get; set; }
        public virtual ICollection<RIM_CATEGORY_LEVEL> RIM_CATEGORY_LEVEL { get; set; }
        public virtual ICollection<RIM_LEVELS> RIM_LEVELS { get; set; }
    }
}
