//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTENNA
    {
        public ANTENNA()
        {
            this.ANTENNA_CELL = new HashSet<ANTENNA_CELL>();
            this.SITE_IDENTITY_ANTENNA = new HashSet<SITE_IDENTITY_ANTENNA>();
            this.SITE_IDENTITY_CHILD_ANTENNA = new HashSet<SITE_IDENTITY_CHILD_ANTENNA>();
        }
    
        public int ID { get; set; }
        public string NE_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_LAST_SERVICE { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public string INVENTORY_UNIT_ID { get; set; }
        public string INVENTORY_UNIT_TYPE { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string UNIT_POSITION { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_UNIT_FAMILY_TYPE { get; set; }
        public string VENDOR_UNIT_TYPE_NUMBER { get; set; }
        public string UNIT_POSITION_FULL { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public string VERSION_NUMBER { get; set; }
    
        public virtual ICollection<ANTENNA_CELL> ANTENNA_CELL { get; set; }
        public virtual ICollection<SITE_IDENTITY_ANTENNA> SITE_IDENTITY_ANTENNA { get; set; }
        public virtual ICollection<SITE_IDENTITY_CHILD_ANTENNA> SITE_IDENTITY_CHILD_ANTENNA { get; set; }
    }
}
