//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_FINANCE_NE
    {
        public int ID { get; set; }
        public int FINANCE_TERM_ID { get; set; }
        public int DATACOM_NE_ID { get; set; }
        public string NE_TYPE { get; set; }
    
        public virtual DATACOM_NE DATACOM_NE { get; set; }
        public virtual DATACOM_FINANCE_TERM DATACOM_FINANCE_TERM { get; set; }
    }
}
