//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIREWALL_PORT
    {
        public int ID { get; set; }
        public int FIREWALL_PORT_TYPE_ID { get; set; }
        public int PORT_ID { get; set; }
        public string RATE_BPS { get; set; }
        public string PORT_LEVEL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> DEPLOYMENT_STATUS { get; set; }
        public int FIREWALL_SUBBOARD_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual FIREWALL_PORT_TYPE FIREWALL_PORT_TYPE { get; set; }
        public virtual FIREWALL_SUBBOARD FIREWALL_SUBBOARD { get; set; }
    }
}
