//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIREWALL_PORT_TYPE
    {
        public FIREWALL_PORT_TYPE()
        {
            this.FIREWALL_PORT = new HashSet<FIREWALL_PORT>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
    
        public virtual ICollection<FIREWALL_PORT> FIREWALL_PORT { get; set; }
    }
}
