//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIREWALL_BOARD_TYPE
    {
        public FIREWALL_BOARD_TYPE()
        {
            this.FIREWALL_BOARD = new HashSet<FIREWALL_BOARD>();
        }
    
        public int ID { get; set; }
        public string ALIAS_NAME { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> TOTAL_SUBSLOTS_NUMBER { get; set; }
    
        public virtual ICollection<FIREWALL_BOARD> FIREWALL_BOARD { get; set; }
    }
}
