//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_NE_SITE
    {
        public int ID { get; set; }
        public int OPTICAL_NE_ID { get; set; }
        public int SITE_CANDIDATE_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RETIRE_DATE { get; set; }
    
        public virtual SITE_CANDIDATE SITE_CANDIDATE { get; set; }
    }
}
