//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_BOARD_TYPE
    {
        public RADIO_BOARD_TYPE()
        {
            this.RADIO_BOARD = new HashSet<RADIO_BOARD>();
        }
    
        public string NAME_NOTE { get; set; }
        public string NAME { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<RADIO_BOARD> RADIO_BOARD { get; set; }
    }
}
