//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE_IDENTITY_CHILD
    {
        public SITE_IDENTITY_CHILD()
        {
            this.CELLs = new HashSet<CELL>();
            this.SITE_IDENTITY_CHILD_ANTENNA = new HashSet<SITE_IDENTITY_CHILD_ANTENNA>();
        }
    
        public int ID { get; set; }
        public string NENAME { get; set; }
        public Nullable<int> SITE_IDENTITY_ID { get; set; }
    
        public virtual ICollection<CELL> CELLs { get; set; }
        public virtual SITE_IDENTITY SITE_IDENTITY { get; set; }
        public virtual ICollection<SITE_IDENTITY_CHILD_ANTENNA> SITE_IDENTITY_CHILD_ANTENNA { get; set; }
    }
}
