//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_NE_PORTS
    {
        public Nullable<int> ID { get; set; }
        public Nullable<int> PORT_ID { get; set; }
        public string PORT_NAME { get; set; }
        public int NE_ID { get; set; }
    }
}
