//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_SUBBOARD_TYPE
    {
        public int ID { get; set; }
        public string ALIAS_NAME { get; set; }
        public string TYPE { get; set; }
        public string PORT_TYPE { get; set; }
        public Nullable<decimal> TOTAL_CHILD_NUMBER { get; set; }
        public Nullable<decimal> RESERVED_SUBSLOT_COUNT { get; set; }
    }
}
