//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_NE
    {
        public OPTICAL_NE()
        {
            this.OPTICAL_FINANCE_NE = new HashSet<OPTICAL_FINANCE_NE>();
            this.OPTICAL_NE_AREA = new HashSet<OPTICAL_NE_AREA>();
            this.OPTICAL_NE_SUBRACK = new HashSet<OPTICAL_NE_SUBRACK>();
            this.OPTICAL_WO_NE = new HashSet<OPTICAL_WO_NE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public string U2000_REF_ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS_NAME { get; set; }
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string PATCH_VERSION { get; set; }
        public string LSR_ID { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string DEPLOYMENT_STATUS { get; set; }
        public string SHELF_TYPE { get; set; }
        public Nullable<int> FIBER_COUNT { get; set; }
        public string GETWAY_TYPE { get; set; }
        public string MODEL { get; set; }
        public Nullable<int> SUB_CATEGORY_ID { get; set; }
    
        public virtual ICollection<OPTICAL_FINANCE_NE> OPTICAL_FINANCE_NE { get; set; }
        public virtual ICollection<OPTICAL_NE_AREA> OPTICAL_NE_AREA { get; set; }
        public virtual ICollection<OPTICAL_NE_SUBRACK> OPTICAL_NE_SUBRACK { get; set; }
        public virtual ICollection<OPTICAL_WO_NE> OPTICAL_WO_NE { get; set; }
    }
}
