//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_CATEGORY_LEVEL
    {
        public RIM_CATEGORY_LEVEL()
        {
            this.RIM_CATEGORY_LEVEL_TYPE = new HashSet<RIM_CATEGORY_LEVEL_TYPE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RIM_CATEGORY_ID { get; set; }
        public Nullable<int> RIM_LEVEL_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<int> LEVEL_ORDER { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> RIM_RELATION_TYPE_ID { get; set; }
        public string JUNCTION_TABLE { get; set; }
    
        public virtual RIM_CATEGORY RIM_CATEGORY { get; set; }
        public virtual RIM_LEVEL RIM_LEVEL { get; set; }
        public virtual RIM_RELATION_TYPE RIM_RELATION_TYPE { get; set; }
        public virtual ICollection<RIM_CATEGORY_LEVEL_TYPE> RIM_CATEGORY_LEVEL_TYPE { get; set; }
    }
}
