//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Syriatel.OSS.API.Models
{
   
    [Table("MW_BOARD")]
    public partial class MW_BOARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MW_BOARD()
        {
            this.MW_NE_BOARD = new HashSet<MW_NE_BOARD>();
            this.MW_PORT = new HashSet<MW_PORT>();
        }
        [Column("ID")]
        public int ID { get; set; }
        [Column("TYPE_ID")]
        public int TYPE_ID { get; set; }
        [Column("SLOT_ID")]
        public string SLOT_ID { get; set; }
        [Column("SOFTWARE_VERSION")]
        public string SOFTWARE_VERSION { get; set; }
        [Column("HARDWARE_VERSION")]
        public string HARDWARE_VERSION { get; set; }
        [Column("BIOS_VERSION")]
        public string BIOS_VERSION { get; set; }
        [Column("FPGA_VERSION")]
        public string FPGA_VERSION { get; set; }
        [Column("SERIAL_NUMBER")]
        public string SERIAL_NUMBER { get; set; }
        [Column("BOM_ITEM")]
        public string BOM_ITEM { get; set; }
        [Column("BARCODE")]
        public string BARCODE { get; set; }
        [Column("DESCRIPTION")]
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> MANUFACTURE_DATE { get; set; }
        [Column("REMARK")]
        public string REMARK { get; set; }
       
        public virtual ICollection<MW_NE_BOARD> MW_NE_BOARD { get; set; }

        public virtual ICollection<MW_PORT> MW_PORT { get; set; }
    }
}
