//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
namespace Syriatel.OSS.API.Models
{
    [Table("MW_NE_TYPE")]
    public partial class MW_NE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MW_NE_TYPE()
        {
            this.MW_NE = new HashSet<MW_NE>();
        }
       [Column("ID")]
        public int ID { get; set; }
        [Column("TYPE")]
        public string TYPE { get; set; }
        [Column("SERIES")]
        public string SERIES { get; set; }
        [Column("VENDOR")]
        public string VENDOR { get; set; }
        [Column("CLASS")]
        public string CLASS { get; set; }
        [Column("MAX_BRD_NMB")]
        public Nullable<int> MAX_BRD_NMB { get; set; }
 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MW_NE> MW_NE { get; set; }
    }
}
