//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
namespace Syriatel.OSS.API.Models
{
    [Table("MW_SFP")]

    public partial class MW_SFP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MW_SFP()
        {
            this.MW_PORT_SFP = new HashSet<MW_PORT_SFP>();
        }
        [Column("ID")]

        public int ID { get; set; }
        [Column("TYPE")]

        public string TYPE { get; set; }
        [Column("SERIAL_NUMBER")]

        public string SERIAL_NUMBER { get; set; }
        [Column("CLEI_CODE")]

        public string CLEI_CODE { get; set; }
        [Column("FIBER_CABLE_TYPE")]

        public string FIBER_CABLE_TYPE { get; set; }
        [Column("BOM_CODE")]

        public string BOM_CODE { get; set; }
        [Column("MANUFACTURER")]

        public string MANUFACTURER { get; set; }
        [Column("MANUFACTURE_DATE")]

        public Nullable<System.DateTime> MANUFACTURE_DATE { get; set; }
        public string DESCRIPTION { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MW_PORT_SFP> MW_PORT_SFP { get; set; }
    }
}
