//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_BOARD
    {
        public DATACOM_BOARD()
        {
            this.DATACOM_BOARD_SUBBOARD = new HashSet<DATACOM_BOARD_SUBBOARD>();
            this.DATACOM_NE_BOARD = new HashSet<DATACOM_NE_BOARD>();
        }
    
        public int ID { get; set; }
        public int DATACOM_BOARD_TYPE_ID { get; set; }
        public decimal SUBRACK_ID { get; set; }
        public decimal SLOT_ID { get; set; }
        public string HARDWARE_VERSION { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string REMARKS { get; set; }
        public string BARCODE { get; set; }
        public string BIOS_VERSION { get; set; }
        public string FPGA_VERSION { get; set; }
        public string STATUS { get; set; }
        public string BOM_ITEM { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> MANUFACTURE_DATE { get; set; }
        public Nullable<decimal> DEPLOYMENT_STATUS { get; set; }
        public Nullable<int> FREE_SUBBOARD { get; set; }
    
        public virtual DATACOM_BOARD_TYPE DATACOM_BOARD_TYPE { get; set; }
        public virtual ICollection<DATACOM_BOARD_SUBBOARD> DATACOM_BOARD_SUBBOARD { get; set; }
        public virtual ICollection<DATACOM_NE_BOARD> DATACOM_NE_BOARD { get; set; }
    }
}
