//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_PORT
    {
        public DATACOM_PORT()
        {
            this.DATACOM_PORT_SFP = new HashSet<DATACOM_PORT_SFP>();
        }
    
        public int ID { get; set; }
        public int DATACOM_PORT_TYPE_ID { get; set; }
        public decimal PORT_ID { get; set; }
        public string PORT_NAME { get; set; }
        public string RATE_BPS { get; set; }
        public string PORT_LEVEL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> DEPLOYMENT_STATUS { get; set; }
        public int DATACOM_SUBBOARD_ID { get; set; }
        public string SUB_TYPE { get; set; }
    
        public virtual DATACOM_SUBBOARD DATACOM_SUBBOARD { get; set; }
        public virtual ICollection<DATACOM_PORT_SFP> DATACOM_PORT_SFP { get; set; }
    }
}
