//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_PORT_OLD
    {
        public MW_PORT_OLD()
        {
            this.MW_PORT_SFP_OLD = new HashSet<MW_PORT_SFP_OLD>();
        }
    
        public int ID { get; set; }
        public int TYPE_ID { get; set; }
        public Nullable<int> PORT_ID { get; set; }
        public string PORT_NAME { get; set; }
        public string PORT_LEVEL { get; set; }
        public string RATE_BPS { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public string REMARK { get; set; }
        public int PARENT_ID { get; set; }
    
        public virtual MW_BOARD_OLD MW_BOARD_OLD { get; set; }
        public virtual ICollection<MW_PORT_SFP_OLD> MW_PORT_SFP_OLD { get; set; }
    }
}
