//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_BOARD_DETAILS
    {
        public string ENGLISH_NAME { get; set; }
        public string SITE_CODE { get; set; }
        public string NENAME { get; set; }
        public string BIOS_VEREX { get; set; }
        public string BIOSVER { get; set; }
        public string BOM_CODE { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public string HARDWARE_VERSION { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public Nullable<int> SLOT_NUMBER { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string VENDOR_NAME { get; set; }
        public string RADIO_BOARD_TYPE_Name { get; set; }
        public string NAME_NOTE { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
