//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_SUBRACK_TYPE
    {
        public RADIO_SUBRACK_TYPE()
        {
            this.RADIO_SUBRACK = new HashSet<RADIO_SUBRACK>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string TYPE_NOTE { get; set; }
    
        public virtual ICollection<RADIO_SUBRACK> RADIO_SUBRACK { get; set; }
    }
}
