//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_ATTRIBUTES
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string ATTR_TYPE { get; set; }
        public Nullable<short> IS_MAIN { get; set; }
        public Nullable<int> ATTR_ORDER { get; set; }
        public Nullable<int> NODE_ID { get; set; }
    
        public virtual RIM_NODE_TABLES RIM_NODE_TABLES { get; set; }
    }
}
