//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_CLASSIFICATION_TABLE
    {
        public RIM_CLASSIFICATION_TABLE()
        {
            this.RIM_CLASSIFICATION_TABLE_TYPE = new HashSet<RIM_CLASSIFICATION_TABLE_TYPE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RIM_CLASSIFICATION_ID { get; set; }
        public Nullable<int> RIM_TABLE_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<int> LEVEL_ORDER { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> RIM_RELATION_TYPE_ID { get; set; }
        public string JUNCTION_TABLE { get; set; }
    
        public virtual RIM_CLASSIFICATION RIM_CLASSIFICATION { get; set; }
        public virtual RIM_TABLE RIM_TABLE { get; set; }
        public virtual RIM_RELATION_TYPE RIM_RELATION_TYPE { get; set; }
        public virtual ICollection<RIM_CLASSIFICATION_TABLE_TYPE> RIM_CLASSIFICATION_TABLE_TYPE { get; set; }
    }
}
