//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE_IDENTITY_WRONG
    {
        public int ID { get; set; }
        public Nullable<int> SITE_CANDIDATE_ID { get; set; }
        public Nullable<int> RADIO_NETYPE_ID { get; set; }
        public Nullable<int> SITE_MODE_ID { get; set; }
        public string NENAME { get; set; }
        public string SITE_MODE_STRING { get; set; }
    }
}
