//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_NE_TYPE
    {
        public DATACOM_NE_TYPE()
        {
            this.DATACOM_NE = new HashSet<DATACOM_NE>();
        }
    
        public int ID { get; set; }
        public string VENDOR { get; set; }
        public string CLASS { get; set; }
        public string SERIES { get; set; }
        public string MODEL { get; set; }
        public Nullable<decimal> TOTAL_CHILD_NUMBER { get; set; }
    
        public virtual ICollection<DATACOM_NE> DATACOM_NE { get; set; }
    }
}
