//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_NE_OLD
    {
        public DATACOM_NE_OLD()
        {
            this.DATACOM_NE_BOARD_OLD = new HashSet<DATACOM_NE_BOARD_OLD>();
            this.DATACOM_NE_SITE_OLD = new HashSet<DATACOM_NE_SITE_OLD>();
        }
    
        public int ID { get; set; }
        public int TYPE_ID { get; set; }
        public decimal U2000_REF_ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS_NAME { get; set; }
        public string SUBRACK_TYPE { get; set; }
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string PATCH_VERSION { get; set; }
        public string LSR_ID { get; set; }
        public string REMARKS { get; set; }
        public Nullable<decimal> DEPLOYMENT_STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> FREE_BOARD { get; set; }
        public Nullable<int> SUB_CATEGORY_ID { get; set; }
    
        public virtual ICollection<DATACOM_NE_BOARD_OLD> DATACOM_NE_BOARD_OLD { get; set; }
        public virtual RIM_SUBCATEGORY RIM_SUBCATEGORY { get; set; }
        public virtual ICollection<DATACOM_NE_SITE_OLD> DATACOM_NE_SITE_OLD { get; set; }
    }
}
