//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_PORT_TYPE
    {
        public OPTICAL_PORT_TYPE()
        {
            this.OPTICAL_PORT = new HashSet<OPTICAL_PORT>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string SUBTYPE { get; set; }
    
        public virtual ICollection<OPTICAL_PORT> OPTICAL_PORT { get; set; }
    }
}
