//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_WORK_ORDER
    {
        public OPTICAL_WORK_ORDER()
        {
            this.OPTICAL_WO_NE = new HashSet<OPTICAL_WO_NE>();
        }
    
        public int ID { get; set; }
        public string WO_DESCRIPTION { get; set; }
    
        public virtual ICollection<OPTICAL_WO_NE> OPTICAL_WO_NE { get; set; }
    }
}
