//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_WO_NE
    {
        public int ID { get; set; }
        public int WO_ID { get; set; }
        public int NE_ID { get; set; }
        public string NE_TYPE { get; set; }
    
        public virtual OPTICAL_NE OPTICAL_NE { get; set; }
        public virtual OPTICAL_WORK_ORDER OPTICAL_WORK_ORDER { get; set; }
    }
}
