//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_NETYPE
    {
        public RADIO_NETYPE()
        {
            this.SITE_IDENTITY = new HashSet<SITE_IDENTITY>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string TYPE_NOTE { get; set; }
        public string SITE_VERSION { get; set; }
    
        public virtual ICollection<SITE_IDENTITY> SITE_IDENTITY { get; set; }
    }
}
