//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_SLOT_DETAILS
    {
        public string ENGLISH_NAME { get; set; }
        public string SITE_CODE { get; set; }
        public string NENAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_LAST_SERVICE { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public Nullable<int> INVENTORY_UNIT_ID { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public Nullable<int> SERIAL_NUMBER { get; set; }
        public Nullable<int> SITE_INDEX { get; set; }
        public Nullable<int> SLOT_NUMBER { get; set; }
        public Nullable<int> SLOT_POSITION { get; set; }
        public string UNIT_POSITION { get; set; }
        public string UNIT_POSITION_FULL { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_UNIT_FAMILY_TYPE { get; set; }
        public string VENDOR_UNIT_TYPE_NUMBER { get; set; }
        public string VERSION_NUMBER { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
