//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAN_SUBRACK
    {
        public RAN_SUBRACK()
        {
            this.RAN_SLOT = new HashSet<RAN_SLOT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SUBRACK_NUMBER { get; set; }
        public string SUBRACK_NAME { get; set; }
        public int RAN_SUBRACK_TYPE_ID { get; set; }
        public string BOM_FRAME_TYPE { get; set; }
        public Nullable<System.DateTime> DATE_OF_LAST_SERVICE { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public string INVENTORY_UNIT_ID { get; set; }
        public string INVENTORY_UNIT_TYPE { get; set; }
        public string ISUUE_NUMBER { get; set; }
        public string BOM_CODE { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public string MODULE_NO { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string UNIT_POSITION { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_UNIT_FAMILY_TYPE { get; set; }
        public string VENDOR_UNIT_TYPE_NUMBER { get; set; }
        public string VERSION_NUMBER { get; set; }
        public string UNIT_POSITION_DETAIL { get; set; }
        public Nullable<int> RACK_FRAME_NO { get; set; }
        public Nullable<int> WORK_MODE_ID { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public Nullable<int> RAN_SUBRACK_HW_TYPE_ID { get; set; }
        public Nullable<int> RAN_SCU_TYPE_ID { get; set; }
    
        public virtual RAN_SCU_TYPE RAN_SCU_TYPE { get; set; }
        public virtual ICollection<RAN_SLOT> RAN_SLOT { get; set; }
        public virtual RAN_SUBRACK_HW_TYPE RAN_SUBRACK_HW_TYPE { get; set; }
        public virtual RAN_SUBRACK_TYPE RAN_SUBRACK_TYPE { get; set; }
    }
}
