//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONE
    {
        public ZONE()
        {
            this.SUBAREAs = new HashSet<SUBAREA>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int AREA_ID { get; set; }
    
        public virtual AREA AREA { get; set; }
        public virtual ICollection<SUBAREA> SUBAREAs { get; set; }
    }
}
