//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAND
    {
        public BAND()
        {
            this.CELLs = new HashSet<CELL>();
        }
    
        public int ID { get; set; }
        public string VALUE { get; set; }
        public string CODE { get; set; }
    
        public virtual ICollection<CELL> CELLs { get; set; }
    }
}
