//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_PORT_SFP
    {
        public int ID { get; set; }
        public int DATACOM_PORT_ID { get; set; }
        public int DATACOM_SFP_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RETIRE_DATE { get; set; }
    
        public virtual DATACOM_PORT DATACOM_PORT { get; set; }
        public virtual DATACOM_SFP DATACOM_SFP { get; set; }
    }
}
