//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_BOARD_SUBBOARD
    {
        public int ID { get; set; }
        public int DATACOM_SUBBOARD_ID { get; set; }
        public int DATACOM_BOARD_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RETIRE_DATE { get; set; }
    
        public virtual DATACOM_BOARD DATACOM_BOARD { get; set; }
        public virtual DATACOM_SUBBOARD DATACOM_SUBBOARD { get; set; }
    }
}
