//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_FINANCE_TERM
    {
        public DATACOM_FINANCE_TERM()
        {
            this.DATACOM_FINANCE_NE = new HashSet<DATACOM_FINANCE_NE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PO_ID { get; set; }
        public Nullable<int> MR_ID { get; set; }
        public Nullable<int> RMR_ID { get; set; }
        public Nullable<int> QUOTATION_ID { get; set; }
    
        public virtual ICollection<DATACOM_FINANCE_NE> DATACOM_FINANCE_NE { get; set; }
    }
}
