//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIREWALL_NE
    {
        public FIREWALL_NE()
        {
            this.FIREWALL_NE_SITE = new HashSet<FIREWALL_NE_SITE>();
            this.FIREWALL_NE_BOARD = new HashSet<FIREWALL_NE_BOARD>();
        }
    
        public int ID { get; set; }
        public int FIREWALL_NE_TYPE_ID { get; set; }
        public decimal U2000_REF_ID { get; set; }
        public string NAME { get; set; }
        public string ALIAS_NAME { get; set; }
        public string REMARKS { get; set; }
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string PATCH_VERSION { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> RIM_SUBCATEGORY_ID { get; set; }
    
        public virtual ICollection<FIREWALL_NE_SITE> FIREWALL_NE_SITE { get; set; }
        public virtual FIREWALL_NE_TYPE FIREWALL_NE_TYPE { get; set; }
        public virtual ICollection<FIREWALL_NE_BOARD> FIREWALL_NE_BOARD { get; set; }
        public virtual RIM_SUBCATEGORY RIM_SUBCATEGORY { get; set; }
    }
}
