//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_NE_TYPE
    {
        public MW_NE_TYPE()
        {
            this.MW_NE = new HashSet<MW_NE>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string SERIES { get; set; }
        public string VENDOR { get; set; }
        public string CLASS { get; set; }
        public Nullable<int> TOTAL_CHILD_NUMBER { get; set; }
    
        public virtual ICollection<MW_NE> MW_NE { get; set; }
    }
}
