//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_NE
    {
        public MW_NE()
        {
            this.MW_NE_BOARD = new HashSet<MW_NE_BOARD>();
            this.MW_NE_SITE = new HashSet<MW_NE_SITE>();
        }
    
        public int ID { get; set; }
        public int MW_NE_TYPE_ID { get; set; }
        public string NE_ID { get; set; }
        public string U2000_REF_ID { get; set; }
        public string NAME { get; set; }
        public string SUBRACK_TYPE { get; set; }
        public string GATEWAY_TYPE { get; set; }
        public string IP { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string PATCH_VERSION { get; set; }
        public string LSR_ID { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string SITE_MODEL { get; set; }
        public string TERMINAL_CLASS { get; set; }
        public Nullable<int> RIM_SUBCATEGORY_ID { get; set; }
    
        public virtual ICollection<MW_NE_BOARD> MW_NE_BOARD { get; set; }
        public virtual MW_NE_TYPE MW_NE_TYPE { get; set; }
        public virtual ICollection<MW_NE_SITE> MW_NE_SITE { get; set; }
    }
}
