//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_NE_SUBRACK
    {
        public int ID { get; set; }
        public int OPTICAL_NE_ID { get; set; }
        public int OPTICAL_SUBRACK_ID { get; set; }
        public System.DateTime CREATE_DATA { get; set; }
        public Nullable<System.DateTime> RETIRE_DATE { get; set; }
    
        public virtual OPTICAL_NE OPTICAL_NE { get; set; }
        public virtual OPTICAL_SUBRACK OPTICAL_SUBRACK { get; set; }
    }
}
