//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_SUBRACK
    {
        public int ID { get; set; }
        public int SUBRACK_NUMBER { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }
        public string BOM_FRAME_TYPE { get; set; }
        public string BOM_CODE { get; set; }
        public string MANUFACTURER_DATA { get; set; }
        public Nullable<int> INVENTORY_UNIT_ID { get; set; }
        public string INVENTORY_UNIT_TYPE { get; set; }
        public string UNIT_POSITION { get; set; }
        public string VENDOR_NAME { get; set; }
        public string UNIT_POSITION_FULL { get; set; }
        public int RADIO_SUBRACK_TYPE_ID { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
    
        public virtual RADIO_SUBRACK_TYPE RADIO_SUBRACK_TYPE { get; set; }
    }
}
