//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADIO_HOSTVER
    {
        public RADIO_HOSTVER()
        {
            this.SITE_IDENTITY_HOSTVER = new HashSet<SITE_IDENTITY_HOSTVER>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string HOST_VER { get; set; }
        public string DESCRIPTION { get; set; }
        public string DETAILS { get; set; }
    
        public virtual ICollection<SITE_IDENTITY_HOSTVER> SITE_IDENTITY_HOSTVER { get; set; }
    }
}
