//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAN_SUBRACK_TYPE
    {
        public RAN_SUBRACK_TYPE()
        {
            this.RAN_SUBRACK = new HashSet<RAN_SUBRACK>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
    
        public virtual ICollection<RAN_SUBRACK> RAN_SUBRACK { get; set; }
    }
}
