//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_SUBCATEGORY
    {
        public RIM_SUBCATEGORY()
        {
            this.DATACOM_NE = new HashSet<DATACOM_NE>();
            this.DATACOM_NE_OLD = new HashSet<DATACOM_NE_OLD>();
            this.FIREWALL_NE = new HashSet<FIREWALL_NE>();
            this.RAN_NETYPE = new HashSet<RAN_NETYPE>();
            this.SITE_MODE = new HashSet<SITE_MODE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> SUBCAT_ORDER { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
    
        public virtual ICollection<DATACOM_NE> DATACOM_NE { get; set; }
        public virtual ICollection<DATACOM_NE_OLD> DATACOM_NE_OLD { get; set; }
        public virtual ICollection<FIREWALL_NE> FIREWALL_NE { get; set; }
        public virtual ICollection<RAN_NETYPE> RAN_NETYPE { get; set; }
        public virtual ICollection<SITE_MODE> SITE_MODE { get; set; }
    }
}
