//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYNC_LOG
    {
        public SYNC_LOG()
        {
            this.SYNC_RECORD_LOG = new HashSet<SYNC_RECORD_LOG>();
        }
    
        public decimal ID { get; set; }
        public decimal OPERATION_ID { get; set; }
        public decimal CATEGORY_ID { get; set; }
        public decimal LEVEL_ID { get; set; }
        public Nullable<decimal> AFFECTED_RECORD { get; set; }
        public short STATUS { get; set; }
        public System.DateTime REQUESTDATE { get; set; }
    
        public virtual SYNC_LEVEL SYNC_LEVEL { get; set; }
        public virtual SYNC_OPERATION SYNC_OPERATION { get; set; }
        public virtual ICollection<SYNC_RECORD_LOG> SYNC_RECORD_LOG { get; set; }
    }
}
