//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIREWALL_SUBBOARD_TYPE
    {
        public FIREWALL_SUBBOARD_TYPE()
        {
            this.FIREWALL_SUBBOARD = new HashSet<FIREWALL_SUBBOARD>();
        }
    
        public int ID { get; set; }
        public string ALIAS_NAME { get; set; }
        public string TYPE { get; set; }
        public string PORT_TYPE { get; set; }
        public Nullable<decimal> TOTAL_PORTS_NUMBER { get; set; }
    
        public virtual ICollection<FIREWALL_SUBBOARD> FIREWALL_SUBBOARD { get; set; }
    }
}
