//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAN_HOSTVER
    {
        public RAN_HOSTVER()
        {
            this.RAN_CONTROLLER_RAN_HOSTVER = new HashSet<RAN_CONTROLLER_RAN_HOSTVER>();
        }
    
        public int ID { get; set; }
        public string HOST_VER { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<RAN_CONTROLLER_RAN_HOSTVER> RAN_CONTROLLER_RAN_HOSTVER { get; set; }
    }
}
