//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_NODE_TABLES
    {
        public RIM_NODE_TABLES()
        {
            this.RIM_ATTRIBUTES = new HashSet<RIM_ATTRIBUTES>();
            this.RIM_LEVEL_NODES1 = new HashSet<RIM_LEVEL_NODES>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> LEVEL_NODE_ID { get; set; }
    
        public virtual ICollection<RIM_ATTRIBUTES> RIM_ATTRIBUTES { get; set; }
        public virtual RIM_LEVEL_NODES RIM_LEVEL_NODES { get; set; }
        public virtual ICollection<RIM_LEVEL_NODES> RIM_LEVEL_NODES1 { get; set; }
    }
}
