//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.RadioOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE_TEST_MHD
    {
        public int ID { get; set; }
        public string SITE_CODE { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string LATITUDE_N { get; set; }
        public string LONGITUDE_E { get; set; }
    }
}
