//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
namespace Syriatel.OSS.API.Models
{
    [Table("MW_PORT_SFP")]

    public partial class MW_PORT_SFP
    {
        [Column("ID")]

        public int ID { get; set; }
        [Column("PARENT_ID")]

        public int PARENT_ID { get; set; }
        [Column("CHILD_ID")]

        public int CHILD_ID { get; set; }
        [Column("CREATE_DATE")]

        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        [Column("RETIRE_DATE")]

        public Nullable<System.DateTime> RETIRE_DATE { get; set; }

        public virtual MW_PORT MW_PORT { get; set; }
        public virtual MW_SFP MW_SFP { get; set; }
    }
}
