//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
namespace Syriatel.OSS.API.Models
{
    [Table("MW_SUBRACK_TYPE")]

    public partial class MW_SUBRACK_TYPE
    {
        [Column("ID")]
        public int ID { get; set; }
        [Column("TYPE")]
        public string TYPE { get; set; }
    }
}
