//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELL
    {
        public CELL()
        {
            this.ANTENNA_CELL = new HashSet<ANTENNA_CELL>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> BAND_ID { get; set; }
        public Nullable<int> SITE_IDENTITY_CHILD_ID { get; set; }
        public string CGI { get; set; }
        public string CELL_NAME { get; set; }
    
        public virtual ICollection<ANTENNA_CELL> ANTENNA_CELL { get; set; }
        public virtual BAND BAND { get; set; }
        public virtual SITE_IDENTITY_CHILD SITE_IDENTITY_CHILD { get; set; }
        public virtual GCELL GCELL { get; set; }
        public virtual UCELL UCELL { get; set; }
    }
}
