//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MW_SFP
    {
        public MW_SFP()
        {
            this.MW_PORT_SFP = new HashSet<MW_PORT_SFP>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string CLEI_CODE { get; set; }
        public string FIBER_CABLE_TYPE { get; set; }
        public string BOM_CODE { get; set; }
        public string MANUFACTURER { get; set; }
        public Nullable<System.DateTime> MANUFACTURE_DATE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<MW_PORT_SFP> MW_PORT_SFP { get; set; }
    }
}
