//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTICAL_SFP
    {
        public OPTICAL_SFP()
        {
            this.OPTICAL_PORT_SFP = new HashSet<OPTICAL_PORT_SFP>();
        }
    
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string CLEI_CODE { get; set; }
        public string FIBER_CABLE_TYPE { get; set; }
        public string BOM_CODES { get; set; }
        public string MANUFACTURE { get; set; }
        public Nullable<System.DateTime> MANUFACTURE_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> DEPLOYMENT_STATUS { get; set; }
    
        public virtual ICollection<OPTICAL_PORT_SFP> OPTICAL_PORT_SFP { get; set; }
    }
}
