//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAN_PORT_WORK_MODE
    {
        public RAN_PORT_WORK_MODE()
        {
            this.RAN_BOARD = new HashSet<RAN_BOARD>();
        }
    
        public int ID { get; set; }
        public string PORT_WORK_MODE { get; set; }
    
        public virtual ICollection<RAN_BOARD> RAN_BOARD { get; set; }
    }
}
