//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAN_CONTROLLER_RAN_HOSTVER
    {
        public int ID { get; set; }
        public Nullable<int> RAN_CONTROLLER_ID { get; set; }
        public Nullable<int> RAN_HOSTVER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RETIRE_DATE { get; set; }
    
        public virtual RAN_CONTROLLER RAN_CONTROLLER { get; set; }
        public virtual RAN_HOSTVER RAN_HOSTVER { get; set; }
    }
}
