//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_TABLE
    {
        public RIM_TABLE()
        {
            this.RIM_ATTRIBUTE = new HashSet<RIM_ATTRIBUTE>();
            this.RIM_CLASSIFICATION_TABLE = new HashSet<RIM_CLASSIFICATION_TABLE>();
            this.RIM_KEYS = new HashSet<RIM_KEYS>();
        }
    
        public int ID { get; set; }
        public string TABLE_NAME { get; set; }
    
        public virtual ICollection<RIM_ATTRIBUTE> RIM_ATTRIBUTE { get; set; }
        public virtual ICollection<RIM_CLASSIFICATION_TABLE> RIM_CLASSIFICATION_TABLE { get; set; }
        public virtual ICollection<RIM_KEYS> RIM_KEYS { get; set; }
    }
}
