//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIM_KEYS
    {
        public int ID { get; set; }
        public string COLUMN_KEY { get; set; }
        public Nullable<int> TABLE_ID { get; set; }
        public string DATATYPE { get; set; }
    
        public virtual RIM_TABLE RIM_TABLE { get; set; }
    }
}
