//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITE_CANDIDATE_DETAILS
    {
        public Nullable<int> AMSL_M { get; set; }
        public Nullable<System.DateTime> APPROVEDBY_DATE { get; set; }
        public Nullable<int> APPROVEDBY_UID { get; set; }
        public string ARABIC_NAME { get; set; }
        public string CANDIDATE_ADDRESS { get; set; }
        public Nullable<int> CANDIDATE_RANKING { get; set; }
        public string COVERED_AREA { get; set; }
        public Nullable<short> CRITICAL_SITE { get; set; }
        public string ENGLISH_NAME { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public string LATITUDE_N { get; set; }
        public string LONGITUDE_E { get; set; }
        public Nullable<System.DateTime> PREPAREDBY_DATE { get; set; }
        public Nullable<int> PREPAREDBY_UID { get; set; }
        public Nullable<System.DateTime> REVIEWEDBY_DATE { get; set; }
        public Nullable<int> REVIEWEDBY_UID { get; set; }
        public Nullable<short> SHELTER_REQUIREMENTS { get; set; }
        public string SITE_CATEGORY_NAME { get; set; }
        public string SITE_CODE { get; set; }
        public string SITE_CONFIGURATION_NAME { get; set; }
        public string VALUE { get; set; }
        public string CONTACT_PERSON_ARABIC_NAME { get; set; }
        public string CONTACT_PERSON_ENGLISH_NAME { get; set; }
        public string CONTACT_PERSON_PHONE { get; set; }
        public string SITE_COVERAGE_TYPE_NAME { get; set; }
        public string SITE_KIND_OF_SUPPORT_NAME { get; set; }
        public string SITE_LOCATION_TYPE_NAME { get; set; }
        public string SITE_PROPERTY_TYPE_NAME { get; set; }
        public string SUBAREA_NAME { get; set; }
        public string ZONE_NAME { get; set; }
        public string AREA_NAME { get; set; }
        public string AREA_ARABIC_NAME { get; set; }
        public string AREA_CODE { get; set; }
        public string REGION_NAME { get; set; }
        public string REGION_CODE { get; set; }
        public string DISPLAY_NAME { get; set; }
        public int ID { get; set; }
        public string NENAME { get; set; }
    }
}
