//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.TranssmissionOSS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYNC_OPERATION
    {
        public SYNC_OPERATION()
        {
            this.SYNC_LOG = new HashSet<SYNC_LOG>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<SYNC_LOG> SYNC_LOG { get; set; }
    }
}
