//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syriatel.OSS.API.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACOM_SUBBOARD_OLD
    {
        public DATACOM_SUBBOARD_OLD()
        {
            this.DATACOM_PORT_OLD = new HashSet<DATACOM_PORT_OLD>();
        }
    
        public int ID { get; set; }
        public int TYPE_ID { get; set; }
        public decimal SUBSLOT_ID { get; set; }
        public string ALIAS_NAME { get; set; }
        public string HARDWARE_VERSION { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string REMARKS { get; set; }
        public string BARCODE { get; set; }
        public string STATUS { get; set; }
        public string BOM_ITEM { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> MANUFACTURE_DATA { get; set; }
        public Nullable<decimal> DEPLOYMENT_STATUS { get; set; }
        public Nullable<int> FREE_PORT { get; set; }
        public Nullable<short> IS_VIRTUAL { get; set; }
    
        public virtual ICollection<DATACOM_PORT_OLD> DATACOM_PORT_OLD { get; set; }
    }
}
